# Archivo de configuración del generador de rutas

[[rutas]]
nombre = "Ruta Yurimaguas"
puntos = ["Yurimaguas" ,"Progreso" ,"Portal" ,"Lagunas" ,"Nucuray" ,"Alianza","Maipuco",
          "San Pedro" ,"Saramuro","Puerto Lima", "Ollanta", "Castilla", "Lisboa","Nauta"]

[[rutas]]
nombre= "Ruta Frontera"
puntos=["Iquitos","Indiana", "Orán","Pebas","Nuevo Pebas","San Francisco","Cochiquinas","San Antonio",
        "Alto Monte","Imasa","San Isidro","San Pablo","Chimbote","Caballococha","San Antonio de Cacao",
        "Puerto Alegría","Santa Rosa"]


# Configuración de naves

[[naves]]
nombre = "Eduardo I"
capacidad = 159

[[naves]]
nombre = "Eduardo II"
capacidad = 159

[[naves]]
nombre = "Eduardo III"
capacidad = 83

[[naves]]
nombre = "Eduardo IV"
capacidad = 83